name:                capistrano-edsl
version:             0.1.0.0
github:              "stackbuilders/capistrano-edsl"
license:             MIT
author:              "Sebastian Estrella"
maintainer:          "sestrella@stackbuilders.com"
copyright:           "2021 Stack Builders Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stackbuilders/capistrano-edsl#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  capistrano-edsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - capistrano-edsl

tests:
  capistrano-edsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - capistrano-edsl
